IAE.Escola.Web/Controllers/ContasController.cs
using IAE.Escola.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IAE.Escola.Web.Controllers
{
    public class ContasController : Controller
    {
      

        // GET: Contad/Create
        public ActionResult Registrar()
        {
            return View("Registrar");
        }

        // POST: Contad/Create
        [HttpPost]
        public ActionResult Registrar(FormCollection collection)
        {
            var IdentityUser = new Identity();


        }

        public ActionResult Login(UsuarioViewModel viewModel)
        {

            if (ModelState.IsValid)
            {

                var userManager = Request
                    .GetOwinContext()
                    .GetUserManager<UserManager<IdentityUser>>();

                var userIdentity = userManager
                    .Find(viewModel.Email, viewModel.Senha);

                if(userIdentity != null)
                {

                    var authManager
                        Request.GetOwinContext().Authentication;
                    var identity =
                        userManager.CreateIdentity(userIdentity, Defaul)
                    
                        authManager.SignIn(new AutenticationProperties
                     {

                        isPersistent = false;

                    }, identity);

                return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return View();

            }
        }

        [Authorize]
        public ActionResult Logoff()
        {
            var authManager = Request.GetOwinContext().Authentication;
            authManager.SignOut();
            return RedirectToAction("Index","Home");

        }
        
    }
}

IAE.Escola.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Alunos", "Index", "Alunos")</li>
                    <li>@Html.ActionLink("Cursos", "Index", "Cursos")</li>
                    <li>@Html.ActionLink("Turmas", "Index", "Turmas")</li>
                    @if(!User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Fazer login", "Login", "Contas")</li>

                    }
                    else
                    {
                        <li>Bem vindo, @User.Identity.Name</li>
                        <li>@Html.ActionLink("Fazer logoff", "Logoff", "Contas")</li>

                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>