IAE.Escola.Web/Models/TurmaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IAE.Escola.Web.Models
{
    public class TurmaViewModel
    {

        public int Id { get; set; }

        [Required (ErrorMessage = "O nome é obrigatorio")]
        [MaxLength(20, ErrorMessage = "O nome da turma pode ter no máximo 20 caracteres")]
        [DisplayName("Nome da turma")]
        public string Nome { get; set; }


        [Required(ErrorMessage = "A flag de ativação é obrigatória")]
        [DisplayName("Turma ativa?")]
        public bool IsAtivo { get; set; }

        public List<AlunoViewModel> Alunos { get; set; }


    }
}

IAE.Escola.Web/Controllers/TurmasController.cs
using AutoMapper;
using IAE.Escola.Dominio;
using IAE.Escola.Repositorio.Entity;
using IAE.Escola.Web.Models;
using IAE.Repository.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace IAE.Escola.Web.Controllers
{
    [Authorize]
    public class TurmasController : Controller
    {

        private IRepositorioGenerico<Turma, int> _repositorioTurma ;
        private IRepositorioGenerico<Aluno, long> _repositorioAluno ;

        public TurmasController(
            IRepositorioGenerico<Turma, int> repositorioTurma,
            IRepositorioGenerico<Aluno, long> repositorioAluno
            )
        {
            _repositorioAluno = repositorioAluno;
            _repositorioTurma = repositorioTurma;

        }

        // GET: Turmas
        public ActionResult Index()
        {
            List<TurmaViewModel> viewModels = Mapper.Map<List<Turma>, List<TurmaViewModel>>(_repositorioTurma.Selecionar());
            return View(viewModels);
        }

        // GET: Turmas/Details/5
        public ActionResult Details(int? id)

        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Turma turma = _repositorioTurma.SelecionarPelaChave(id.Value);
            TurmaViewModel viewModel = Mapper.Map<Turma, TurmaViewModel>(turma);  
            return View(viewModel);
        }

        [Authorize(Roles = "ADMIN")]
        public ActionResult Create()
        {
            return View();
        }


        [Authorize(Roles = "ADMIN")]
        // POST: Turmas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Exclude =  "IsAtivo")]TurmaViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                Turma novaTurma = Mapper.Map<TurmaViewModel, Turma> (viewModel);
                novaTurma.IsAtivo = true;
                _repositorioTurma.Inserir(novaTurma);
                return RedirectToAction("Index");
            }
            else
            {
                return View(viewModel);

            }

        }

        // GET: Turmas/Edit/5
        public ActionResult Edit(int id)
        {
            Turma turma = _repositorioTurma.SelecionarPelaChave(id);
            TurmaViewModel viewModel = Mapper.Map<Turma, TurmaViewModel>(turma);
            return View(viewModel);
        }

        // POST: Turmas/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind( Include = "Id,Nome,IsAtivo")]TurmaViewModel viewModel)
        {
            if (ModelState.IsValid)

                    {

                Turma turma
                    = Mapper.Map<TurmaViewModel, Turma>(viewModel);
                _repositorioTurma.Atualizar(turma);
                return RedirectToAction("Index");

            }
            else

            {

                return View(viewModel);
            }
        }

        // GET: Turmas/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Turmas/Delete/5
        [HttpPost]
        [ActionName("Delete")]

        public ActionResult DeleteConfirmed(int id)
        {


            Turma turma = _repositorioTurma.SelecionarPelaChave(id);
            _repositorioTurma.Deletar(turma);
            return RedirectToAction("Index");

        }

        public ActionResult AdicionarAlunos(int turmaId)
        {

            Turma turma = _repositorioTurma.SelecionarPelaChave(turmaId);
            TurmaViewModel viewModel = Mapper.Map<Turma, TurmaViewModel>(turma);
            List<AlunoViewModel> alunos = Mapper.Map<List<Aluno>, List<AlunoViewModel>>(_repositorioAluno.Selecionar().Where(a => a.TurmaId == null).ToList());

            //ViewData["ListaAlunos"] = alunos;
            ViewBag.ListaAlunos = new SelectList(alunos, "Id", "Nome");
           return View(viewModel);

        }


        [HttpPost]
        public ActionResult AdicionarAluno(int idTurma, long idAluno)

        {
            Aluno aluno = _repositorioAluno.SelecionarPelaChave(idAluno);
            aluno.TurmaId = idTurma;
            _repositorioAluno.Atualizar(aluno);
            return new HttpStatusCodeResult(HttpStatusCode.OK);

        }


    }
}

IAE.Escola.Web/Views/Turmas/AdicionarAlunos.cshtml
@model IAE.Escola.Web.Models.TurmaViewModel

@{
    ViewBag.Title = "AdicionarAlunos";
}

<h2>Adicionar alunos</h2>


<div class="row">
    <div class="col-md-9">

        @Html.DropDownList("idAluno", (SelectList)ViewBag.ListaAlunos, new { @class = "form-control", id = "cmbAlunos" })

    </div>

    <div class="col-md-3">
        <button class="btn btn-default" id="btnVincular">Vincular!</button>

    </div>
</div>


<table class="table" id="tblAlunos">
    <thead>
        <tr>
            <th>
                Nome do aluno
            </th>
      
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.Alunos)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>           
            </tr>
        }
    </tbody>

</table>

@section scripts {
    
    <script type="text/javascript">

        $(document).ready(function () {
            $("#btnVincular").click(function () {
                var aluno = $("#cmbAlunos").val();
                var turma = @Model.Id;
                $.ajax({
                method: "POST", 
                url: "@Url.Action("AdicionarAluno", "Turmas")",
                data: {idTurma: turma, idAluno: aluno},
                success: function() {

                    var nomeAluno = $("#cmbAlunos option:selected").text();
                    $("#cmbAlunos option:selected").remove();
                    $("#tblAlunos > tbody").append(
                        "<tr>" +
                        "   <td>" +
                        "       " + nomeAluno +
                        "</tr>"

                     );



                }    ,
                error: function() {
                    alert("Deu ruim!");

                    }

                })
            });
        });

    </script>
    
    }

IAE.Escola.Web/Views/Turmas/Create.cshtml
@model IAE.Escola.Web.Models.TurmaViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TurmaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IAE.Escola.Web/Views/Turmas/Delete.cshtml
@model IAE.Escola.Web.Models.TurmaViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TurmaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAtivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAtivo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(p => p.Id)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

IAE.Escola.Web/Views/Turmas/Details.cshtml
@model IAE.Escola.Web.Models.TurmaViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TurmaViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsAtivo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsAtivo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

IAE.Escola.Web/Views/Turmas/Edit.cshtml
@model IAE.Escola.Web.Models.TurmaViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TurmaViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsAtivo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsAtivo)
                    @Html.ValidationMessageFor(model => model.IsAtivo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

IAE.Escola.Web/Views/Turmas/Index.cshtml
@model IEnumerable<IAE.Escola.Web.Models.TurmaViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsAtivo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsAtivo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |
            @Html.ActionLink("Adicionar alunos", "AdicionarAlunos", new { turmaId = item.Id})
        </td>
    </tr>
}

</table>